config/routes.rb
Rails.application.routes.draw do

  post '/cohorts/:cohort_id/send_mail', to: 'students#send_mail', as: 'send_email'

  get 'home/index'

  resources :code_challenges

  resources :announcements


  resources :cohorts do
    resources :students  do
      collection { post :import }
    end
  end

  root to: "home#index"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :cohort
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.where(meetup: false)
    @meetups = Announcement.where(meetup: true)
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to root_path, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to root_path, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:date, :title, :location, :cohort_id, :description, :event_url)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcements.html.erb
  <% @announcements.where(meetup: false).order(:date).each do |announ| %>
    <li class="collection-item">
      <table class="bordered">
        <tbody>
          <tr>
            <td>Date/Time: <%= announ.date.strftime('%m/%d/%Y') %></td>
          </tr>
          <% if announ.event_url? %>
          <tr>
            <td>Event: <%= link_to announ.title, announ.event_url %></td>
          </tr>
          <% else %>
          <tr>
            <td>Event: <%= announ.title %></td>
          </tr>
          <% end %>
          <% if announ.location? %>
          <tr>
            <td>Location: <%= announ.location %></td>
          </tr>
          <% end %>
          <% if announ.description? %>
          <tr>
            <td><%= announ.description.html_safe %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </li>
  <% end %>

app/views/announcements/_form.html.erb
<%= simple_form_for(@announcement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date, as: 'string', label: 'Event Date', input_html: { class: 'datepicker' } %>
    <%= f.input :title %>
    <%= f.input :location %>
    <%= f.association :cohort, label_method: :start_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/announcements/_meetups.html.erb
  <% @meetups.order(:date).each do |announ| %>
    <li class="collection-item">
      <table class="bordered">
        <tbody>
          <tr>
            <td><h5><%= link_to announ.title, announ.event_url %></h5></td>
          </tr>
          <tr>
            <td>Group: <%= announ.host_group %></td>
          </tr>
          <tr>
            <td>When: <%= announ.date.strftime('%m/%d/%Y - %l:%M %p') %></td>
          </tr>

          <% if announ.location? %>
          <tr>
            <td>Where: <%= announ.location %></td>
          </tr>
          <% end %>
          <% if announ.description? %>
          <tr>
            <td><%= announ.description.html_safe %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </li>
  <% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.date %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.location %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Announcement', new_announcement_path, class:'btn' %>
<br>
<h1>Meetups</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetups.each do |announcement| %>
      <tr>
        <td><%= announcement.date %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.location %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @announcement.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @announcement.location %>
</p>

<p>
  <strong>Cohort:</strong>
  <%= @announcement.cohort %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>