config/routes.rb
Rails.application.routes.draw do

  post '/cohorts/:cohort_id/send_mail', to: 'students#send_mail', as: 'send_email'

  get 'home/index'

  resources :code_challenges

  resources :announcements


  resources :cohorts do
    resources :students  do
      collection { post :import }
    end
  end

  root to: "home#index"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :users, through: :user_cohorts
  has_many :user_cohorts, dependent: :destroy
  has_many :students
  has_many :announcements, dependent: :destroy
  has_many :sent_emails, dependent: :destroy
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = current_user.cohorts.all
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
    @students = @cohort.students.all
    @students_with_no_items =  @cohort.students.no_todos
    @students_with_open_items =  @cohort.students.open_todos
    @email_sent_today = @cohort.sent_emails.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
  end

  # GET /cohorts/1/edit
  def edit
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @city = current_user.city
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        @cohort.users << @city.users
        format.html { redirect_to @cohort, notice: 'Cohort was successfully created.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohort }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params.require(:cohort).permit(:start_date, :user_id, :email_body)
    end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_edit_email_body.html.erb
<%= simple_form_for(@cohort, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email_body, :autofocus=>true %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, data: { "disable-with": "Saving..."  } %>
  </div>
<% end %>

app/views/cohorts/_form.html.erb
<%= simple_form_for(@cohort) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_date, as: 'string', label: 'Start Date', input_html: { class: 'datepicker' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<h1>Editing Cohort</h1>

<div class="row">
  <%= render 'form', cohort: @cohort %>
</div>



<div class="row">
  <%= link_to 'Delete Cohort', cohort_path(@cohort),
              class: "btn red",
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

app/views/cohorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohorts</h1>

<ul class="collection with-header">
  <li class="collection-header"><h4><%= current_user.name %> Cohorts</h4></li>
  <% @cohorts.each do |cohort| %>
    <li class="collection-item"><%= link_to cohort.start_date.strftime('%m/%d/%Y'), cohort_path(cohort) %></li>
  <% end %>
</ul>

<br>

<%= link_to 'New Cohort', new_cohort_path, class: "btn" %>

app/views/cohorts/new.html.erb
<h1>New Cohort</h1>

<%= render 'form', cohort: @cohort %>

<%= link_to 'Back', cohorts_path %>

app/views/cohorts/show.html.erb
<div class="row">
  <h4><%= @cohort.start_date.strftime('%m/%d/%Y') %> Cohort -   <%= link_to "Edit Cohort", edit_cohort_path(@cohort), class: "btn" %>
</h4>
</div>
<div class="row">
  <div class="divider"></div>
</div>
<div class="row">
  <h5>All the Student Things</h5>
</div>

<div class="row">
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">thumb_down</i>Students With Outstanding Items - <%= @students_with_open_items.count %></div>
      <div class="collapsible-body"><span>
        <ul class="collection">
          <% @students_with_open_items.each do |student| %>
            <li class="collection-item">
              <%= link_to student.name, cohort_student_path(@cohort, student) %> | <%= mail_to student.email, student.email %> <br>

              <%= render partial: "students/student_updates", locals: {student: student} %>
            </li>
          <% end %>
        </ul>
      </span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">thumb_up</i>Students Complete With Paperwork - <%= @students_with_no_items.count %></div>
      <div class="collapsible-body"><span>
        <ul class="collection">
          <% @students_with_no_items.each do |student| %>
            <li class="collection-item">
              <%= link_to student.name, cohort_student_path(@cohort, student) %> | <%= mail_to student.email, student.email %> <br>

              <%= render partial: "students/student_updates", locals: {student: student} %>

            </li>
          <% end %>
        </ul>
      </span></div>
    </li>
  </ul>
</div>


<div class="row">
  <%= form_tag "/cohorts/#{@cohort.id}/students/import", method: :post, class: 'dropzone form', id: 'media-dropzone' do %>
    <div class="dz-message" data-dz-message><span>Yo! Drop Dat CSV, Tho</span></div>
    <div class="fallback">
      <%= file_field_tag 'media', multiple: true %>
    </div>
  <% end %>
</div>



<div class="row">
  <div class="divider"></div>
</div>
<div class="row">
  <h5>All the Email Things</h5>
</div>

  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Edit The Body of All Emails</div>
      <div class="collapsible-body"><span>
        <div class="row">
          <%= render partial: "edit_email_body", locals: {cohort: @cohort} %>
        </div>
      </span></div>
    </li>
    <li><div class="collapsible-header"><i class="material-icons">filter_drama</i>Last Email Sent: <%= @cohort.sent_emails.last.created_at.strftime('%m/%d/%Y') if @cohort.sent_emails.present? %></div></li>
  </ul>

<div class="row">
  <div class="divider"></div>

</div>
  <div class="row">
    <%= link_to "Send Weeks Emails", send_email_path(@cohort), class: "btn #{'disabled' if @email_sent_today.present?}", method: :post, data: { confirm: 'Are you sure?', "disable-with": "Sending..." }%>
  </div>