config/routes.rb
Rails.application.routes.draw do

  post '/cohorts/:cohort_id/send_mail', to: 'students#send_mail', as: 'send_email'

  get 'home/index'

  resources :code_challenges

  resources :announcements


  resources :cohorts do
    resources :students  do
      collection { post :import }
    end
  end

  root to: "home#index"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort

  scope :ok_to_email, -> { where(do_not_send: false)   }

  scope :open_todos, -> {
      where(down_payment: false)
      .or(where(enrollment_agreement: false))
      .or(where(transcript: false))
      .or(where(financially_cleared: false))
    }

  scope :no_todos, -> {
      where(down_payment: true)
      .where(enrollment_agreement: true)
      .where(transcript: true)
      .where(financially_cleared: true)
    }

  require 'csv'

  def self.import(file, cohort)
    CSV.foreach(file.path, headers: true) do |row|
      student = cohort.students.find_or_initialize_by(email: row['Email'])
      student.first_name = row['First Name']
      student.last_name = row['Last Name']
      student.enrollment_agreement = row['Student Has Signed Student Agreement?'] == 'Yes'
      student.down_payment = row['Most Current Financial Detail: Deposit Paid?'] == '1'
      student.financially_cleared = row['Financial Status'] == 'Financially Cleared'
      student.yes_we_code = row['Financial Status'] == 'Full Tuition Grant'
      student.save!
    end
  end



  def name
    "#{first_name} #{last_name}"
  end

  def self.todos(student, date)
    todos = []
    unless student.down_payment?
      todos << "You can pay your downpayment here: <a href='https://app.moonclerk.com/pay/fbd0e7p7iuo'>https://app.moonclerk.com/pay/fbd0e7p7iuo</a>.".html_safe
    end
    unless student.enrollment_agreement?
      todos << "Make sure that you have signed your enrollment agreement. You can find the link in your acceptance email."
    end
    unless student.transcript?
      todos << "You can send Christie your transcripts at <a href='mailto:christie@theironyard.com?subject=Transcripts'>christie@theironyard.com</a>.".html_safe
    end
    unless student.financially_cleared?
      todos << "Please ensure that your tuition arrangments are made by #{(date - 5.days).strftime('%m/%d/%Y')}. You can contact <a href='mailto:finance@theironyard.com'>finance@theironyard.com</a> for help.".html_safe
    end
    todos
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  include ActionView::Helpers::DateHelper

  # GET /students
  # GET /students.json
  def index
    @cohort = Cohort.find(params[:cohort_id])
    @students = @cohort.students.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @cohort = Cohort.find(params[:cohort_id])
    @time_to_class = distance_of_time_in_words(Date.today, @cohort.start_date)
    @weekly_challenge = CodeChallenge.weekly(@cohort.start_date)
    @announcements = @cohort.announcements.where(meetup: false).where('date > ?', Date.today).where('date < ?', Date.today + 3.weeks)
    @todos = Student.todos(@student, @cohort.start_date)
    @meetups = @cohort.announcements.where(meetup: true).where('date > ?', Date.today).where('date <= ?', Date.today + 8.days)
  end

  def send_mail
    @cohort = Cohort.find(params[:cohort_id])
    @students = @cohort.students
    @students.ok_to_email.each do |student|
      StudentMailer.weekly_mailer(@cohort, student).deliver_later
    end
    @cohort.sent_emails.create!()
    redirect_to cohort_path(@cohort), notice: "Done and Done."
  end

  def import
    @cohort = Cohort.find(params[:cohort_id])
    @file = params[:file]
    if Student.import(@file, @cohort)
      redirect_to cohort_path(@cohort), notice: "Done and Done."
    end
  end

  # GET /students/new
  def new
    @cohort = Cohort.find(params[:cohort_id])
    @student = @cohort.students.new
  end

  # GET /students/1/edit
  def edit
    @cohort = Cohort.find(params[:cohort_id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
     @student.update(student_params)
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :down_payment, :financially_cleared, :enrollment_agreement, :transcript, :yes_we_code, :cohort_id, :do_not_send)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for([@cohort, @student]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :down_payment %>
    <%= f.input :financially_cleared %>
    <%= f.input :enrollment_agreement %>
    <%= f.input :transcript %>
    <%= f.input :yes_we_code %>
    <%= f.association :cohort %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/_student_updates.html.erb
<%= simple_form_for([@cohort, student], remote: true) do |f| %>
  <div class="col">
    <%= f.input :transcript, input_html: { id: "transcript-#{student.id}" }  %>
  </div>
  <div class="col">
    <%= f.input :do_not_send, label: "Do Not Send Email", input_html: { id: "dont_send-#{student.id}" }  %>
  </div>
  <br> <br>
  <div class="row">
    <div class="form-actions">
      <%= f.button :submit, data: { "disable-with": "Saving..." } %>
    </div>
  </div>



<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Down payment</th>
      <th>Financially cleared</th>
      <th>Enrollment agreement</th>
      <th>Transcript</th>
      <th>Yes we code</th>
      <th>Cohort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.down_payment %></td>
        <td><%= student.financially_cleared %></td>
        <td><%= student.enrollment_agreement %></td>
        <td><%= student.transcript %></td>
        <td><%= student.yes_we_code %></td>
        <td><%= student.cohort %></td>
        <td><%= link_to 'Show', cohort_student_path(@cohort, student) %></td>
        <td><%= link_to 'Edit', edit_cohort_student_path(@cohort, student) %></td>
        <td><%= link_to 'Destroy', cohort_student_path(@cohort, student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_cohort_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

app/views/students/show.html.erb
<div class="row">
  <p>Greetings, <%= @student.first_name %>!</p>

  <p><%= @cohort.email_body %></p>

<ul class="collection with-header">
  <li class="collection-header"><h4>Your weekly code challenge:</h4></li>
  <li class="collection-item"><%= link_to @weekly_challenge.description, @weekly_challenge.newline_url %></li>
</ul>

<% if @announcements.where(meetup: false).present? %>
  <ul class="collection with-header">
    <li class="collection-header"><h4>A Few Announcements:</h4></li>
    <%= render 'announcements/announcements' %>
  </ul>
<% end %>

<% if @todos.present? %>
  <ul class="collection with-header">
    <li class="collection-header"><h4>A Few Gentle Reminders:</h4></li>
    <% @todos.each do |todo| %>
      <li class="collection-item"><%= todo %></li>
    <% end %>
  </ul>
<% end %>

  <ul class="collection with-header">
    <li class="collection-header"><h4>Meetups Worth Attending</h4></li>
    <%= render 'announcements/meetups' %>
  </ul>


</div>