config/routes.rb
Rails.application.routes.draw do

  post '/cohorts/:cohort_id/send_mail', to: 'students#send_mail', as: 'send_email'

  get 'home/index'

  resources :code_challenges

  resources :announcements


  resources :cohorts do
    resources :students  do
      collection { post :import }
    end
  end

  root to: "home#index"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cohorts = current_user.cohorts.all
    @cohort = @cohorts.last
    @cohort_announcements = Announcement.where(cohort_id: @cohorts.pluck(:id))
    @weekly_challenge = CodeChallenge.weekly(@cohort.start_date)
    @announcements = @cohort_announcements.where(meetup: false)
    @meetups = @cohort_announcements.where(meetup: true).where(date: Date.today.beginning_of_week..Date.today.end_of_week)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <h4><%= current_user.city.name %></h4>
</div>

<div class="row">
  <ul class="collection with-header">
    <li class="collection-header"><h4>Cohorts</h4></li>
    <% @cohorts.each do |cohort| %>
      <li class="collection-item"><%= link_to cohort.start_date.strftime('%m/%d/%Y'), cohort_path(cohort) %></li>
    <% end %>
  </ul>
</div>

<div class="row">
  <%= link_to "New Cohort", new_cohort_path, class: "btn" %>
</div>

<% if @announcements.present? %>
<div class="row">
  <ul class="collection with-header">
    <li class="collection-header"><h4>Upcomming Announcements</h4></li>
    <%= render 'announcements/announcements' %>
  </ul>
</div>
<% end %>

<div class="row">
  <%= link_to "New Announcement", new_announcement_path, class: "btn" %>
</div>


<div class="row">
  <ul class="collection with-header">
    <li class="collection-header"><h4>Code Challenges</h4></li>
    <li class="collection-item"><%= @weekly_challenge.description if @weekly_challenge.present? %> <%= link_to "Edit", edit_code_challenge_path(@weekly_challenge), class: "btn" if @weekly_challenge.present? %></li>
  </ul>
</div>

<div class="row">
  <%= link_to "New Code Challenge", new_code_challenge_path, class: "btn " %>
</div>

<% if @meetups.present? %>
<div class="row">
  <ul class="collection with-header">
    <li class="collection-header"><h4>Meetups Worth Attending</h4></li>
    <%= render 'announcements/meetups' %>
  </ul>
</div>
<% end %>